 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: 07HypeR/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: 07HypeR
            # Text on contribution graph 
            text: ABHIK
       - uses: 07HypeR/07HypeR@v1
       
       name: Reddit Meme

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  deploy:
    name: Update Reddit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Reddit
        uses: d3code/github-action-readme-reddit-meme@latest
        with:
          commit_author: Luke Sands
          commit_email: luke.sands@d3code.com.au
